animation_images:
  type: objects
  default: []
  schema:
    name: image
    properties:
      image:
        type: upload
        required: true
      xOffset:
        type: float
        default: 0
      yOffset:
        type: float
        default: 0
      scale:
        type: float
        default: 1
        validations:
          min: 0.1
          max: 5

display_mode:
  default: "first visit and first like or solution"
  type: enum
  choices:
    - "first visit"
    - "first like or solution"
    - "first visit and first like or solution"
    - "every other day and first solution"
  description: The animation will display once daily per browser, based on this action

test_mode:
  default: false
  description: when enabled, the animation will show more than once per day
