animation_images:
  default: "[]"
  json_schema: >-
    {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "src": {
            "type": "string",
            "minLength": 1,
            "description": "Image source (upload to a staff topic to keep local)"
          },
          "xOffset": {
            "type": "number",
            "description": "Offset multiplier relative to viewport (0-2)"
          },
          "yOffset": {
            "type": "number",
            "description": "Offset multiplier relative to viewport (0-2)"
          }
        },
        "additionalProperties": false
      }
    }

display_mode:
  default: "first visit and first like or solution"
  type: enum
  choices:
    - "first visit"
    - "first like or solution"
    - "first visit and first like or solution"
    - "every other day and first solution"
  description: The animation will display once daily per browser, based on this action

test_mode:
  default: false
  description: when enabled, the animation will show more than once per day
